baseURL = "https://ryanfleck.ca/"
languageCode = "en-us"
title = "Ryan Fleck"
theme = "ascetic"
paginate = 10 
pygmentsCodeFences = true
pygmentsStyle = "perldoc"

[permalinks]
    posts = "/:year/:filename"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[markup.goldmark.renderer]
    unsafe = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
