baseURL = "https://ryanfleck.ca/"
languageCode = "en-us"
title = "Ryan Fleck"
theme = "ascetic"
paginate = 10 
pygmentsCodeFences = true
pygmentsStyle = "perldoc"

[permalinks]
    posts = "/:year/:filename"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[markup.goldmark.renderer]
    unsafe = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "lanczos"
# Default JPEG quality setting. Default is 75.
quality = 90 
anchor = "smart"
bgColor = "#ffffff"

[imaging.exif]
includeFields = ""
disableDate = true 
disableLatLong = true 