baseURL = "https://ryanfleck.ca/"
languageCode = "en-us"
title = "Ryan Fleck"
theme = "ascetic"
paginate = 10 
pygmentsCodeFences = true
pygmentsStyle = "emacs"

[permalinks]
    posts = "/:year/:title"

[markup]
    defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
    unsafe = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true